### ISSUE TITLE
SyntaxError: Unexpected token function

### ISSUE THREAD

**Issue by szare** [Raathigesh/react-automate#1]
After run, I receiving the following error:
/Users/szz/WebstormProjects/react-automate/src/Container.js:36
    value: async function execute(payload) {
                 ^^^^^^^^
SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at loader (/Users/szz/WebstormProjects/react-automate/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/szz/WebstormProjects/react-automate/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by Raathigesh** [comment]
That's unfortunate. Did you try running `yarn start` after a `yarn install`?

**Comment by Raathigesh** [comment]
And you need Node v8.
